name: Demo Test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'


jobs:
  Test-Google-Test:
    runs-on: ubuntu-latest

    steps:
      - name: Hello Step
        run: echo "Hello World"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake g++
          sudo apt-get install libgtest-dev


      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make all

      - name: run the tests
        run: |
          cd build
          ./tst/GTest_GItHub_Actions_Example_tst